### ISSUE TITLE
Visualise predictions 

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/predict_pv_yield#74]
Visualise predictions by comparing pv yield predictions with the truth.

Could also at the end of a training run / end of each epoch save plot these to neptune

**Comment by JackKelly** [comment]
Don't worry, the code already plots a comparison of the prediction vs the ground truth during the validation runs, and sends this plot to Neptune :)

![image](https://user-images.githubusercontent.com/460756/131988125-29c3e7c3-731e-4aa3-b591-af1fd14b6039.png)

Taken from https://app.neptune.ai/o/OpenClimateFix/org/predict-pv-yield/e/PRED-99/all?path=validation%2Fplot&attribute=epoch6

**Comment by peterdudfield** [comment]
Ah, ok, maybe I need to turn that back on

I wanted a few extra things too, like this

<img width="1408" alt="Screenshot 2021-09-03 at 11 05 20" src="https://user-images.githubusercontent.com/34686298/131988448-2824a3d2-354f-4b4d-8123-bd14fc963f2f.png">

**Comment by JackKelly** [comment]
nice!

(And I think that behaviour is quite common in CNN models when used for nowcasting:  It learns to draw a pretty accurate 'straight line', but doesn't get the high-frequency changes due to small clouds moving overhead, possibly because the CNN can't learn to 'focus' on the most relevant pixels of the image!  CNNs with pooling are great for image classification, where it's fine to throw away precise positional information (who cares where exactly the dog is in the image?!) but, for nowcasting, I think attention is pretty important to learn to dynamically focus on the important pixels.... sorry, this is a bit off-topic for this issue!)

**Comment by peterdudfield** [comment]
No, I agree, the CNN probably are not be powerful enough here, I'm interested to get this plotting for the Perciever Model

**Comment by JackKelly** [comment]
> get this plotting for the Perciever Model

That'd be awesome!  So cool to see this stuff coming together!  Thank you!

**Comment by peterdudfield** [comment]
Yea, just slowly adding more and more tooling which will all be useful
